---
name: Build Container Images for JCoCo

on:
  push:
    paths:
      - jcoco/**

jobs:
  build-and-push-container-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    steps:
      - name: Get code from the repository
        uses: actions/checkout@v1

      - name: Set up QEMU for cross-platform builds
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "386,arm,arm64,ppc64le"

      - name: Set up Docker Buildx for cross-platform builds
        uses: docker/setup-buildx-action@v2

      - name: login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3.1.1
        with:
          context: jcoco
          file: jcoco/Containerfile
          platforms:
            - linux/amd64,linux/386,linux/arm64,linux/arm/v7,linux/ppc64le
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/jcoco:latest
